### ISSUE TITLE
Document getting py-spy to work with z2jh

### ISSUE THREAD

**Issue by mriedem** [IBM/jupyter-tools#6]
py-spy gets installed automatically with z2jh [1] but that doesn't make it automatically work. There are changes that need to be made in the helm chart hub config:

```yaml
  containerSecurityContext:
    allowPrivilegeEscalation: true
    capabilities:
      drop:
      - all
      add:
      # py-spy needs SYS_PTRACE to be able to read process memory
      - SYS_PTRACE
```

And there are changes needed in the hub docker image:

```Dockerfile
# The SYS_PTRACE capability is required to run py-spy as a normal user.
# For Kubernetes this must be accompanied by a securityContext configuration
# in the pod spec.
RUN setcap cap_sys_ptrace+ep $(which py-spy)
RUN setcap cap_sys_ptrace+ep $(which strace)
```

We should document that either in here or in the z2jh docs.

[1] https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/images/hub/requirements.in

FYI @rmoe
